pipeline {
    agent any
    environment {
        MVN_HOME = tool(name: '3.9.8', type: 'maven')
    }
    stages {
        stage('Build') {
            steps {
                script {
                    env.PATH = "${MVN_HOME}/bin:${env.PATH}"
                }
                dir("simple-java-maven-app") {
                    sh 'mvn -B -DskipTests clean package'
                }
            }
        }
        stage('Test') {
            steps {
                script {
                    env.PATH = "${MVN_HOME}/bin:${env.PATH}"
                }
                dir("simple-java-maven-app") {
                    sh 'mvn test'
                }
            }
            post {
                always {
                    junit 'simple-java-maven-app/target/surefire-reports/*.xml'
                }
            }
        }
        stage('Deliver') {
            steps {
                sh './jenkins/scripts/deliver.sh'
            }
        }
    }
}
