pipeline {
    agent any
    stages {
        stage('Build') {
            steps {
                script {
                    // Use the Maven version you configured in Jenkins
                    def mvnHome = tool(name: 'Maven 3.9.8', type: 'maven')
                    env.PATH = "${mvnHome}/bin:${env.PATH}"
                }
                dir("simple-java-maven-app") {
                    sh 'mvn -B -DskipTests clean package'
                }
            }
        }
        stage('Test') {
            steps {
                script {
                    // Ensure Maven 3.9.8 is still in use
                    def mvnHome = tool(name: 'Maven 3.9.8', type: 'maven')
                    env.PATH = "${mvnHome}/bin:${env.PATH}"
                }
                sh 'mvn test'
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
        stage('Deliver') {
            steps {
                sh './jenkins/scripts/deliver.sh'
            }
        }
    }
}
